# Site settings
title: "Zoomer Ecology"
#email: jacob@jacobtomlinson.co.uk
description: "An Evolutionary Framework for the social ecology of Generation Z"
domain: zoomerecology.github.io
baseurl: ""
url: https://zoomerecology.github.io 
title_description: "An Evolutionary Framework for the Social Ecology of Generation Z - the last generation."
title_image: "/images/17316.jpg"

#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/zoomerecology/zoomerecology.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5
future: True

# Social usernames/URLs
#twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
#instagram_username: 
#reddit_username: 
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
#xing_link:
#facebook_link:

# Footer
footer_left: "&copy; 2022 a Teutonic Knight"
footer_right: "Contact: 100501103+zoomerecology@users.noreply.github dot com"
#footer_right: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noir</a> theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

#permalink: pretty
permalink: /:title/
exclude: [vendor]

plugins:
  - jekyll-sitemap